### ISSUE TITLE
Compile affogato for target arm64-apple

### ISSUE THREAD

**Issue by lorenzocerrone** [constantinpape/affogato#23]
Hi Constantin,

I tried to install `affogato` on a M1 mac, but there is no native `osx-arm64` target.  I tried to install it using the x64 emulation and works, but then I have other problems with other dependencies like napari. 

Would it be possible (and straight forward)  to compile `affogato` for `osx-arm64`? 

If you need help testing, I have access to an M1 mac. 

Best, 
Lorenzo

**Comment by constantinpape** [comment]
I think it's possible to do this by updating the conda-forge recipe. I don't have any time to look into it though, but a PR to the feedstock that makes the `osx-arm64` target available would be welcome.
https://github.com/conda-forge/affogato-feedstock

**Comment by lorenzocerrone** [comment]
Update:
I opened a migration PR https://github.com/conda-forge/conda-forge-pinning-feedstock/pull/4039 
following this guide:
https://conda-forge.org/blog/posts/2020-10-29-macos-arm64/

**Comment by constantinpape** [comment]
This is done.
